### ISSUE TITLE
Ability to log in via beeminder oauth

### ISSUE THREAD

**Issue by szymonkorytnicki** [szymonkorytnicki/beeminder-ui#30]
- [x] api.php - allow subset of methods and params from beeminder api
- [x] update JS to work locally
- [x] login page in react
- [x] first deploy to bui.interestingprojects.net
- [x] handle case when cookie is not valid and redirect to login
- [x] handle callback.php not working (tweak cra proxy settings)
- [x] don't use/secure env file
- [x] security http headers?

other:

- [x] update readme
- [ ] ability to log out
