### ISSUE TITLE
Complete pre release checklist

### ISSUE THREAD

**Issue by szymonkorytnicki** [szymonkorytnicki/beeminder-ui#33]
After merging #30 first release should have:

- [x] merge #30 
- [x] merge #23 
- [x] ability to log in using my account
- [ ] create new account, create sample goal, log in
- [ ] UI check on Windows / Edge
- [ ] UI check on Android
- [ ]
